import React, { useState, useEffect } from 'react'
import './App.css'
import './AppChatHyde.css'

/**
 * HyDE tab — shows standard RAG vs HyDE retrieval side by side.
 *
 * Standard: embed the raw query → retrieve.
 * HyDE: generate a hypothetical answer → embed that → retrieve.
 * The hypothetical document is shown so learners understand what was embedded.
 */

const EXAMPLES = [
  'How does the CSS box model work?',
  'What is the difference between let and const?',
  'Explain the Fetch API',
  'How do Promises work in JavaScript?',
]

function DocList({ docs, label, color }) {
  return (
    <div className="hyde-doc-list">
      <div className="hyde-col-heading" style={{ borderColor: color }}>
        <span className="hyde-stage" style={{ color }}>{label}</span>
        <span className="hyde-doc-count">{docs.length} docs retrieved</span>
      </div>
      {docs.map((doc, i) => (
        <DocCard key={i} doc={doc} rank={i + 1} color={color} />
      ))}
    </div>
  )
}

function DocCard({ doc, rank, color }) {
  const [expanded, setExpanded] = useState(false)
  return (
    <div className="hyde-doc-card">
      <div className="hyde-doc-header" onClick={() => setExpanded(v => !v)}>
        <span className="hyde-rank" style={{ background: color + '22', color }}>#{rank}</span>
        <span className="hyde-filepath">{doc.filepath?.split('/').pop() || doc.id}</span>
        <span className="hyde-score">{doc.score}</span>
        <span className="hyde-expand">{expanded ? '▲' : '▼'}</span>
      </div>
      {expanded && <p className="hyde-doc-content">{doc.content?.slice(0, 400)}{doc.content?.length > 400 ? '…' : ''}</p>}
    </div>
  )
}

function AppChatHyde() {
  const [query, setQuery] = useState('')
  useEffect(() => {
    const h = (e) => setQuery(e.detail)
    window.addEventListener('infopanel:question', h)
    return () => window.removeEventListener('infopanel:question', h)
  }, [])
  const [result, setResult] = useState(null)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState(null)

  const search = async (q) => {
    const text = q || query
    if (!text.trim()) return
    setQuery(text)
    setIsLoading(true)
    setError(null)
    setResult(null)
    try {
      const response = await fetch('/api/chat-hyde', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ q: text }),
      })
      if (!response.ok) throw new Error('Request failed')
      setResult(await response.json())
    } catch {
      setError('Request failed. Please try again.')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="app hyde-app">
      {/* Query bar */}
      <div className="hyde-query-bar">
        <input
          className="hyde-input"
          value={query}
          onChange={e => setQuery(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && search()}
          placeholder="Ask a web development question…"
        />
        <button className="hyde-btn" onClick={() => search()} disabled={isLoading || !query.trim()}>
          {isLoading ? 'Running…' : 'Compare →'}
        </button>
      </div>
      <div className="hyde-examples">
        {EXAMPLES.map((ex, i) => (
          <button key={i} className="example-btn" onClick={() => search(ex)}>{ex}</button>
        ))}
      </div>

      {error && <div className="hyde-error">{error}</div>}

      {result && (
        <div className="hyde-layout">
          {/* Hypothetical doc */}
          <div className="hyde-hyp-section">
            <span className="hyp-label">Hypothetical document generated by LLM (this is what gets embedded for HyDE)</span>
            <blockquote className="hyp-doc">{result.hypothetical_doc}</blockquote>
          </div>

          {/* Side-by-side retrieval */}
          <div className="hyde-comparison">
            <DocList docs={result.standard_docs} label="Standard RAG" color="#6366f1" />
            <div className="hyde-vs">vs</div>
            <DocList docs={result.hyde_docs} label="HyDE" color="#0891b2" />
          </div>

          {/* Answer */}
          {result.answer && (
            <div className="hyde-answer">
              <span className="hyde-answer-label">Answer (from HyDE-retrieved docs)</span>
              <p className="hyde-answer-text">{result.answer}</p>
            </div>
          )}
        </div>
      )}

      {!result && !isLoading && (
        <div className="hyde-placeholder">
          Ask a question to compare standard query embedding vs. hypothetical document embedding.
        </div>
      )}
    </div>
  )
}

export default AppChatHyde
